# Generated by Django 4.2.5 on 2023-09-20 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('netflixAccount', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='User ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('videoUrl', models.URLField(max_length=500)),
                ('thumbnailUrl', models.URLField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
